#服务配置
spring:
  application:
    name: micr-task
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.88.128:8848
        username: nacos
        password: 203417
server:
  port: 8086
  servlet:
    context-path: /task