server:
  port: 9000
  servlet:
    context-path: /pay

#关闭模板引擎缓存
spring:
  thymeleaf:
    cache: false
  application:
    name: micr-pay
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.88.128:8848
        username: nacos
        password: 203417
  #redis配置
  redis:
    host: 192.168.88.128
    port: 6379
